### ISSUE TITLE
keyu lab 1

### ISSUE THREAD

**Issue by wuk19** [DataScience4Psych/lab-01-hello-r#10]
https://github.com/wuk19/keyu-lab-1.git

**Comment by wuk19** [comment]
Hi Mason, this is my updated lab 1 and please let me know if you have further questions!

**Comment by smasongarrison** [comment]
Could you grant me access to the lab? I cannot see it.

![image](https://user-images.githubusercontent.com/6001608/107458848-e2057280-6b22-11eb-889b-eacf1b420ede.png)

**Comment by wuk19** [comment]
Could you please try it again now and see if it works?

Keyu.

**Comment by smasongarrison** [comment]
I can see it now. I'll take a look at it soon

**Comment by smasongarrison** [comment]
I included comments on your repo, but I'll still count this as satisfactory. https://github.com/wuk19/keyu-lab-1/commit/bdab2a41fc99894c6827388ca24beb88fdd57be7#commitcomment-46988229
