### ISSUE TITLE
Annie Lab 1 - Hello R

### ISSUE THREAD

**Issue by anniehsom** [DataScience4Psych/lab-01-hello-r#7]
[https://github.com/anniehsom/lab-01-hello-r](url)

**Comment by smasongarrison** [comment]
(I made a comment with my suggestions... https://github.com/anniehsom/lab-01-hello-r/commit/7fa70de8de5cc507bd4bc7913b58c5ec8d444c7a#commitcomment-46982128)

**Comment by smasongarrison** [comment]
Yep Yep -- satisfactory!
