### ISSUE TITLE
Natalie Frye Lab 1

### ISSUE THREAD

**Issue by ngfrye** [DataScience4Psych/lab-01-hello-r#8]
[https://github.com/ngfrye/lab-01-hello-r](url)

@smasongarrison

**Comment by smasongarrison** [comment]
See comments on your repo: https://github.com/ngfrye/lab-01-hello-r/commit/ca449300fa0f25a47c8869f3ff4d03b89a0069da#commitcomment-46988136

**Comment by smasongarrison** [comment]
Thanks!
