### ISSUE TITLE
Vanessa Gill Lab 1

### ISSUE THREAD

**Issue by nesssleee** [DataScience4Psych/lab-01-hello-r#9]
https://github.com/nesssleee/lab-01-hello-r

**Comment by smasongarrison** [comment]
great! I'm planning on giving everybody feedback soon...

**Comment by smasongarrison** [comment]
See comments: https://github.com/nesssleee/lab-01-hello-r/commit/858760cecf37120ccd7c652c0c35aa7cee5e2fbe#commitcomment-46982254

**Comment by smasongarrison** [comment]
:D
